
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
== Exported Fields

This document describes the fields that are exported by Countbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-common>>
* <<exported-fields-count>>

[[exported-fields-beat]]
=== Beat Fields

Contains common beat fields available in all event types.



==== beat.name

The name of the Beat sending the log messages. If the shipper name is set in the configuration file, then that value is used. If it is not set, the hostname is used.


==== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


==== @timestamp

type: date

example: 2015-01-24 14:06:05.071000

format: YYYY-MM-DDTHH:MM:SS.milliZ

required: True

The timestamp when the event log record was generated.


==== tags

Arbitrary tags that can be set per Beat and per transaction type.


==== fields

type: dict

Contains user configurable fields.


[[exported-fields-common]]
=== Common Fields

Contains common fields available in all event types.



==== module

The name of the module that generated the event.


==== metricset

The name of the metricset that generated the event.


==== metricset-host

Hostname of the machine from which the metricset was collected. This field may not be present when the data was collected locally.


==== rtt

type: long

required: True

Event round trip time in microseconds


==== type

example: metricsets

required: True

The document type. Always set to "metricsets".


[[exported-fields-count]]
=== Count Fields

Count metrics



=== count Fields

Count contains count statistics



=== increment Fields

`increment` contains a continuously incrementing counter.



==== count.increment.counter

type: long

Incrementing counter.


